theme = ["reveal-hugo"]
baseurl = "http://localhost"

[logo]
src = "tr-logo.png"
alt = "health cards logo" # Alt text. 
width = "15%" # Size of the file.
diag = "1%" # How far from the top right should the file be.
top = "1%" # Overrides diag.
right = "1%" # Overrides diag.

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

# use Hugo's hl in markdown (with or without a language tag)
[markup.highlight]
codeFences = true
style = "reveal-hugo"
